accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

mango_plane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spots/', include('spots.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

spots/urls.py
from django.urls import path
from . import views
app_name = 'spots'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update_spot/', views.update_spot, name='update_spot'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:spot_pk>/', views.detail, name='detail'),
    path('<int:spot_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:spot_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:spot_pk>/likes/',views.likes, name='likes'),
    path('<int:spot_pk>/comments/<int:comment_pk>/likes/',views.comment_likes, name = 'comment_likes'),
    path('search/', views.search, name='search'),
    path('delete_recently_viewed_spots/', views.delete_recently_viewed_spots, name='delete_recently_viewed_spots'),
    path('city/', views.city, name='city'),
    ]

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

  <style>
    body {
      font-family: 'Noto Sans KR', sans-serif;
    }
    .tab-content {
      display: none;
    }
    .nav {
      position: fixed;
      top: 0;
      left: 0;
      width:100%;
      background-color: rgba(0, 0, 0, 0);
    }
    .nav-link{
      color: white;
    }
    .modal-backdrop {
      z-index: 1059;
    }
    
    .modal-content {
      z-index: 1060;
    }
  {%block style%}
  {%endblock style%}
  </style>
</head>
<body>
  <nav class="navbar navbar-expand nav">
    <div class="d-flex container-fluid" >
      <a class="me-auto navbar-brand" href="{% url 'spots:index' %}">
        <img src="{% static 'logo3.png' %}" alt="logo" width="151">
      </a>
      {% comment %} <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> {% endcomment %}
      <div class="ms-3" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'spots:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'spots:create' %}">작성하기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
          </li>
        </ul>
      </div>
      {% if request.user.is_authenticated %}
      {% comment %} <p class="fs-6 mb-0 mx-2" style="vertical-align: middle">{{ user }}님 안녕하세요. </p> {% endcomment %}
        <!-- Button trigger modal -->
        <button type="button" style="width: 70px; height: 70px; padding: 0;" class="btn btn-lg rounded-circle" data-bs-toggle="modal" data-bs-target="#exampleModal">
          {% if user.image %}
          <img class="rounded-circle" style="width: 100%; height: 100%; object-fit: cover;" src="{{ user.image.url }}" alt="Profile Image">
          {% else %}
          <img class="rounded-circle" style="width: 100%; height: 100%; object-fit: cover;" src="{% static 'not-found-user.png' %}" alt="Profile Image">
          {% endif %}
        </button>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-10" aria-labelledby="exampleModalLabel" aria-hidden="true" style = "z-index:2000" >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button style = "width : 50%" onclick="openTab(event, 'tab1')">최근 본 맛집</button>
                <button style = "width : 50%" onclick="openTab(event, 'tab2')">가고싶다</button>
              </div>
              <div class="modal-body">
                <!-- 탭 컨텐츠 -->
                <div id="tab1" class="tab-content" style="display: block">
                  <p>최근 본 맛집 탭</p>
                </div>
                <div id="tab2" class="tab-content">
                
                  {% if liked_spots %}
                    <ul>
                      {% for spot in liked_spots %}
                      <a href="{% url 'spots:detail' spot.pk %}">
                        <li>{{ spot.title }}</li>
                      </a>
                      {% endfor %}
                    </ul>
                  {% endif %}

                </div>
              </div>
              <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">내 정보</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content" style = "z-index:2000">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">내 정보</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class = "container text-center">
                  <div style = "display: inline-block;">
                  <div class="card" class = "mx-auto" style = "width : 400px;">
                    {% if request.user.image %}
                      <img src="{{ request.user.image.url }}" class="card-img-top rounded-2 mx-auto mt-4" style = "width: 300px;" alt="image">
                    {% else %}
                      <img src="{% static 'not-found-user.png' %}" class="card-img-top rounded-2 mx-auto mt-4" alt="image">
                    {% endif %}
                    <div class="card-body mal">
                      <h4 class="card-text card_title">{{ request.user }}</h4>
                      <p class="card-text">{{spot.title}}</p>
                      <p class="card-text">이름: {{ request.user.last_name }}{{ request.user.first_name }}</p> 
                      <p class="card-text">이메일: {{ request.user.email }}</p> 
                    </div>
                  </div>
                  <div class = 'd-flex justify-content-evenly'>
                    {% comment %} <a href="{% url #%}">
                      <button type="button" class="btn btn-danger m-3">비밀번호 변경</button>
                    </a> {% endcomment %}
                    <form action="{% url 'accounts:delete' %}" method="POST">
                      {% csrf_token %}
                      <input type="submit" class="btn btn-danger m-3" value="회원탈퇴">
                    </form>
                    <a class="btn btn-danger m-3" href="{% url 'accounts:logout' %}" role="button">로그아웃</a>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <a class="btn btn-outline-dark-subtle mx-2" href="{% url 'accounts:login' %}" role="button">로그인</a>
        <a class="btn btn-outline-dark" href="{% url 'accounts:signup' %}" role="button">회원가입</a>
      {% endif %}
    </div>
  </nav>
  {%block content%}
  {%endblock content%}

  <script>
		// 탭을 열기 위한 함수
		function openTab(evt, tabName) {
			var i, tabcontent, tablinks;
			tabcontent = document.getElementsByClassName("tab-content");
			for (i = 0; i < tabcontent.length; i++) {
				tabcontent[i].style.display = "none";
			}
			tablinks = document.getElementsByTagName("button");
			for (i = 0; i < tablinks.length; i++) {
				tablinks[i].className = tablinks[i].className.replace(" active", "");
			}
			document.getElementById(tabName).style.display = "block";
			evt.currentTarget.className += " active";
		}; 

    window.addEventListener('scroll', function() {
      var navLinks = document.querySelectorAll('.nav-link');
      var currentPosition = window.scrollY;
      
      if (currentPosition <= 250) {
        navLinks.forEach(function(link) {
          link.style.color = 'white';
        });
      } else {
        navLinks.forEach(function(link) {
          link.style.color = 'black';
        });
      }
    });
	</script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>